# docker pull postgres:15-alpine
version: '3.1'

services:

  db:
    image: postgres:15-alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: hcrm
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

# docker run -d \
# 	--name some-postgres \
# 	-e POSTGRES_PASSWORD=mysecretpassword \
# 	-e PGDATA=/var/lib/postgresql/data/pgdata \
# 	-v /custom/mount:/var/lib/postgresql/data \
# 	postgres

# For example, to add an additional user and database, add the following to /docker-entrypoint-initdb.d/init-user-db.sh:

# #!/bin/bash
# set -e

# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
# 	CREATE USER docker;
# 	CREATE DATABASE docker;
# 	GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
# EOSQL
