# TODO: jwtkey set to random but better get from secret storage or env vars
server:
  host: 0.0.0.0
  port: 8088
  db: "enabled"
  timeout:
    read: 15
    write: 15

auth:
  signing_key: "PopsoyfridnimivRikFadtindyuspac!"
  hash_salt: "your_hash_salt"
  token_ttl: 86400

# Database settings
# I suppose to use one DB postgresql by default
postgresql:
  user: "admin"
  password: "example"
  host: "127.0.0.1"
  port: "5432"
  db: "hcrm"
  sslmode: "disable"
  pool:
    MaxIdleConns: 3            # seconds
    ConnMaxIdleTime: 10        # seconds
    MaxOpenConns: 10           # seconds
    ConnMaxLifetime: 60        # minutes

mongo:
  uri: "mongodb://auth-mongo:27017"
  name: "authorizer"
  collection: "users"
